name: Build and Release .NET Framework 4.7.2 Project

on:
  workflow_dispatch:  # 手动触发器

jobs:
  build:
    runs-on: windows-latest  # 使用Windows平台进行编译

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用Python 3.x版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖包，列出并安装

      - name: Update version in csproj
        run: |
          python ./update_version.py ./OsEasy_Cloud_ToolBox/OsEasy_Cloud_ToolBox.csproj  # 更新版本号

      - name: Build the project
        run: |
          msbuild ./OsEasy_Cloud_ToolBox/OsEasy_Cloud_ToolBox.csproj /p:Configuration=Release

      - name: Create release tag
        run: |
          version=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('./OsEasy_Cloud_ToolBox/OsEasy_Cloud_ToolBox.csproj'); root = tree.getroot(); print(root.find('.//Version').text.strip())")
          git tag "v$version"  # 创建新的tag

      - name: Publish release on GitHub
        run: |
          version=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('./OsEasy_Cloud_ToolBox/OsEasy_Cloud_ToolBox.csproj'); root = tree.getroot(); print(root.find('.//Version').text.strip())")
          changelog=$(git log --pretty=format:'- %s (%h, @%an)' --no-merges)
          gh release create "v$version" ./bin/Release/OsEasy_Cloud_ToolBox.exe --title "$version" --notes "# $version\n## 提交记录\n$changelog"  # 发布新版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于创建发行版

      - name: Clean up
        run: |
          del /q .\OsEasy_Cloud_ToolBox\bin\Release\*
