name: Build and Publish Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  update_version_and_publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果需要额外的依赖可以在此处添加

      - name: Run Python script to update version
        run: |
          python update_version.py
          
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.2'
        
      - name: Build the project
        run: |
          msbuild OsEasy_Cloud_ToolBox.sln /p:Configuration=Release

      - name: Create a new Git tag
        id: create_tag
        run: |
          VERSION=$(python -c "import re; version = open('OsEasy_Cloud_ToolBox/Properties/AssemblyInfo.cs').read(); match = re.search(r'AssemblyVersion\(\"([^\"]+)\"\)', version); print(match.group(1))")
          git tag "v$VERSION"
          git push origin "v$VERSION"
        
      - name: Generate Release Notes
        id: release_notes
        run: |
          VERSION=$(python -c "import re; version = open('OsEasy_Cloud_ToolBox/Properties/AssemblyInfo.cs').read(); match = re.search(r'AssemblyVersion\(\"([^\"]+)\"\)', version); print(match.group(1))")
          git log --oneline --no-merges --pretty=format:'- %s (#%h, @%an)' > release_notes.md
          echo "# $VERSION" > release_notes.md

      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/Release/OsEasy_Cloud_ToolBox.exe
            release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
