name: Build and Release

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Update version number
      id: version
      run: |
        python update_version.py
        echo "VERSION=$(cat Properties/AssemblyInfo.cs | grep -oP '\d+\.\d+\.\d+\.\d+' | head -n 1)" >> $GITHUB_ENV

    - name: Set up MSBuild for .NET Framework
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build the project
      run: |
        msbuild /p:Configuration=Release OsEasy_Cloud_ToolBox.csproj

    - name: Create Git tag
      run: |
        git tag v$VERSION
        git push origin v$VERSION

    - name: Create a GitHub release
      uses: ghcrowd/create-release@v1.0.1
      with:
        tag_name: v$VERSION
        release_name: $VERSION
        body: |
          # $VERSION
          ## Commit Records
          $(git log --oneline --pretty=format:"- %s (#%h, @%an)" --no-merges $(git describe --tags --abbrev=0)..HEAD)
        files: |
          OsEasy_Cloud_ToolBox/bin/Release/OsEasy_Cloud_ToolBox.exe
          $(git ls-files | grep -e '\.cs$')

    - name: Clean up
      run: |
        git tag -d v$VERSION
        git push origin :refs/tags/v$VERSION
