name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment version
        run: |
          pip install chardet
          python ./.github/workflows/increment_version.py
      - name: Set up .NET Framework
        run: |
          $ErrorActionPreference = "Stop"
          curl https://aka.ms/vs/17/release/vs_BuildTools.exe -O '.\vs_installer.exe'
          Start-Process ".\vs_installer.exe" -ArgumentList "--quiet", "--norestart", "--path cache" -Wait

      - name: Install MSBuild
        run: |
          # 安装MSBuild
          choco install msbuild
      - name: Build project
        run: msbuild /t:Rebuild /p:Configuration=Release
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.increment_version.outputs.new_version }}"
          release_name: "${{ steps.increment_version.outputs.new_version }}"
          body: |
            # ${{ steps.increment_version.outputs.new_version }}
            ## 提交记录
            ${{ steps.get_commits.outputs.commits }}
      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          path: 'bin/Release/*.exe'
      - id: get_commits
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog
          file: CHANGELOG.md
          commit: false
