name: Build and Release

on:
  workflow_dispatch:  # 手动触发器

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 可以根据需要选择Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt  # 如果有依赖文件

      - name: Run version updater script
        run: python version_updater.py

      - name: Build the project
        run: |
          msbuild /p:Configuration=Release /p:Platform="x64" "OsEasy_Cloud_ToolBox.sln"

      - name: Create a new Git tag
        id: create_tag
        run: |
          VERSION=$(python -c "import json; print(json.load(open('version.json'))['version'])")  # 获取更新后的版本号
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG

      - name: Generate release notes
        run: |
          VERSION=$(python -c "import json; print(json.load(open('version.json'))['version'])")
          git log --oneline --no-merges --pretty=format:"- %s (%h by %an)" > release_notes.md
          echo "# $VERSION" > release_notes.md
          echo "## 提交记录" >> release_notes.md
          cat release_notes.md

      - name: Create a GitHub release
        uses: gh_action/github-release-action@v1
        with:
          tag_name: v${{ steps.create_tag.outputs.tag }}
          release_name: v${{ steps.create_tag.outputs.tag }}
          body_path: release_notes.md
          files: |
            ./bin/Release/OsEasy_Cloud_ToolBox.exe  # 编译后的exe文件路径
            ./src/OsEasy_Cloud_ToolBox.zip  # 代码压缩包路径

